version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-new-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smanager_db
      MYSQL_USER: smanager
      MYSQL_PASSWORD: smanager
    ports:
      - "3307:3306"  # Porta externa:porta interna
    volumes:
      - mysql-data:/var/lib/mysql

  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: jaeger
    ports:
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

volumes:
  mysql-data:
