version: '3.8'

services:

  mysql:
    image: mysql:8.0.22
    container_name: sales-management-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: smanager
      MYSQL_PASSWORD: smanager
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smanagement_db