version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-new-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smanager_db
      MYSQL_USER: smanager
      MYSQL_PASSWORD: smanager
    ports:
      - "3307:3306"  # Porta externa:3306 interna
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
